blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/wez/weenyterm/discussions
    about: When you have questions that are not bug reports or feature requests
  - name: WeenyTerm room on Matrix/Element
    url: https://app.element.io/#/room/#weenyterm:matrix.org
    about: if you'd prefer more realtime conversation with the community
