[package]
name = "rangeset"
version = "0.1.0"
authors = ["Weeny Furlong <weeny@weenyfurlong.org>"]
edition = "2018"

[dependencies]
num = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "rangeset"
harness = false

